### ISSUE TITLE
add pretty stuff

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/bridge#1]
for example, btn hue-shifting and blur?

``` css
p {
    -webkit-filter: blur(2px) grayscale(.5) opacity(0.8);
}

/* hue-shift on brand-primary colored elements */
.btn:hover {
    -webkit-filter: hue-rotate(360deg);

    -webkit-transition: all 10s linear;
    -moz-transition: all 10s linear;
    -o-transition: all 10s linear;
    -ms-transition: all 10s linear;
    transition: all 10s linear;
}
```

or the parallax squares on the sides of [this devblog](http://www.hexahedria.com/).
